# Site settings
title: DIVESH SONI
email: dsoni@caltech.edu
description: > # this means to ignore newlines until "baseurl:"
  Divesh Soni is a second year graduate student at California Institute of Technology. He has 9+ years of experience in the aerospace industry/academia. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
linkedin_username: jekyllrb
github_username:  divesh04

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Ph.D. candidate"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""