# Site settings
title: DIVESH SONI
email: dsoni@caltech.edu
description: > # this means to ignore newlines until "baseurl:"
  This website is inspired from a template by Steven V. Miller [svmiller.github.io](http://svmiller.github.io)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
linkedin_username: jekyllrb
github_username:  divesh04

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Ph.D. candidate"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""